version: 2

updates:
  # Server dependencies (Node.js)
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "saifyxpro"
    reviewers:
      - "saifyxpro"
    commit-message:
      prefix: "server"
      prefix-development: "server"
      include: "scope"
    labels:
      - "dependencies"
      - "server"
      - "automated"
    ignore:
      # Ignore major version updates for stability
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Client dependencies (React)
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "saifyxpro"
    reviewers:
      - "saifyxpro"
    commit-message:
      prefix: "client"
      prefix-development: "client"
      include: "scope"
    labels:
      - "dependencies"
      - "client"
      - "automated"
    ignore:
      # Ignore major version updates for stability
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    assignees:
      - "saifyxpro"
    reviewers:
      - "saifyxpro"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "automated"

  - package-ecosystem: "docker"
    directory: "/client"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    assignees:
      - "saifyxpro"
    reviewers:
      - "saifyxpro"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "automated"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
    assignees:
      - "saifyxpro"
    reviewers:
      - "saifyxpro"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
